# =================================================================================================
# File: checklist_module.R
# Description: A reusable Shiny module for running progress checks for FishSET projects
#
# Authors: Paul Carvalho, Anna Abelman
# Date created: 7/29/2025
# Dependencies: 
# Notes: 
# =================================================================================================

# Checklist helper functions ----------------------------------------------------------------------
# icon_wrapper
# Description: Wrapper function for icon
# Parameters: 
# - icon_name: character representing the name of the icon
# - icon_color: character representing the name of the color for the icon
# Returns: an icon object
icon_wrapper <- function(icon_name, icon_color) {
  icon(name = icon_name, 
       lib = "font-awesome", 
       style = paste0("color: ", icon_color, "; font-size: 30px;"))
}

# pass_icon
# Description: This function returns icons to be displayed in the progress check popup, and 
#              ets color based on pass/fail of checklist tests.
# Parameters:
# - type: character representing which list element to evaluate from the output generated by the 
#         checklist() function
# - project_checklist: list generated by the checklist() function that contains checkpoints 
#         and status
# Returns: an icon object to be displayed in the progress check popup
pass_icon <- function(tab, checklist) {
  # Get progress checks for tab
  list_index <- which(names(checklist) == tab)
  list_name <- names(checklist)[list_index]
  list_checks <- checklist[[list_index]]
  
  # Initialize empty output message
  out_icon_message <- NULL
  
  # Load data
  if (tab == "load_data") {
    if (all(unlist(list_checks))) {
      out_icon <- icon_wrapper(icon_name = "file-arrow-up", icon_color = "green")
      
    } else if (any(unlist(list_checks))) {
      out_icon <- icon_wrapper(icon_name = "file-arrow-up", icon_color = "#F5CF27")
      
      failed_checks <- names(which(list_checks == FALSE))
      
      if (any(failed_checks %in% c("maint_data", "spat_data"))){
        out_icon_message <- "Load the required data"
        
      } else if (any(failed_checks %in% ("sel_vars"))) {
        out_icon_message <- 
          "Select and save variables"
      }
      
    } else {
      out_icon <- icon_wrapper(icon_name = "file-arrow-up", icon_color = "black")    
    }
  }
  
  # QAQC
  if (tab == 'qaqc') {
    out_icon <- icon_wrapper(icon_name = "magnifying-glass-chart", icon_color = "black")
  }
  
  # Format data
  if (tab == "format_data"){
    out_icon <- icon_wrapper(icon_name = "file-lines", icon_color = "black")
  }
  
  # Models data
  if (tab == "models"){
    out_icon <- icon_wrapper(icon_name = "gears", icon_color = "black")
  }
  
  # Policy data
  if (tab == "policy"){
    out_icon <- icon_wrapper(icon_name = "fish-fins", icon_color = "black")
  }
  
  return(list(
    out_icon,
    out_icon_message
  ))
}

# Checklist UI ------------------------------------------------------------------------------------
# Description: Creates action button to check progress of a project. When clicked a modal will
#              popup to display checklist/progress.
checklist_ui <- function(id){
  ns <- NS(id)
  
  actionButton(ns("checklist_btn"), "Check progress", class = "btn-primary") 
}


# Checklist Server --------------------------------------------------------------------------------
# Description: Shows a modal popup that displays progress for the current project
checklist_server <- function(id, rv_project_name, rv_data){
  moduleServer(id, function(input, output, session){
    ns <- session$ns
    
    # Initialize reactives
    rv_project_checklist <- reactiveValues(
      checklist = list(
        load_data = list(
          main_data = FALSE,
          spat_data = FALSE,
          sel_vars = FALSE),
        
        qaqc = list(
          tmp_check = FALSE),
        
        format_data = list(
          tmp_check = FALSE),
        
        models = list(
          tmp_check = FALSE),
        
        policy = list(
          tmp_check = FALSE)
      )
    )
    
    # Display progress check popup for current project
    observeEvent(input$checklist_btn, {
      # Check input reactives are available
      req(rv_project_name)
      req(rv_data) 
      project_name <- rv_project_name()$value
      
      ## Load data checks -------------------------------------------------------------------------
      # Check if main and spat data in reactive value are NULL
      if (!is.null(rv_data$main)) {
        rv_project_checklist$checklist$load_data$main_data <- TRUE
      }
      
      if (!is.null(rv_data$spat)) {
        rv_project_checklist$checklist$load_data$spat_data <- TRUE
      }
      
      # Check if selected variables file exists
      if (!is_empty(project_name)) {
        tab_name <- paste0(project_name, "SavedVariables.rds")
        file_name <- file.path(loc_data(project_name), tab_name)  
        
        if (file.exists(file_name)) {
          rv_project_checklist$checklist$load_data$sel_vars <- TRUE
          
        } else {
          rv_project_checklist$checklist$load_data$sel_vars <- FALSE
        }
        
      } else {
        rv_project_checklist$checklist$load_data$sel_vars <- FALSE
      }
      
      # Generate check list icons based on checks
      load_icon <- pass_icon("load_data", rv_project_checklist$checklist)
      qaqc_icon <- pass_icon("qaqc", rv_project_checklist$checklist)
      format_icon <- pass_icon("format_data", rv_project_checklist$checklist)
      models_icon <- pass_icon("models", rv_project_checklist$checklist)
      policy_icon <- pass_icon("policy", rv_project_checklist$checklist)
      
      # Display progress check UI
      showModal(
        modalDialog(
          title = "Project progress",
          
          tags$div(
            fluidRow(
              # Load data check
              column(1, load_icon[[1]]), 
              column(1, icon(
                name = "arrow-right", 
                lib = "font-awesome", 
                style = "color: black; font-size: 30px;")),
              
              # QAQC check
              column(1, qaqc_icon[[1]]), 
              column(1, icon(
                name = "arrow-right", 
                lib = "font-awesome", 
                style = "color: black; font-size: 30px;")),
              
              # Format data check
              column(1, format_icon[[1]]), 
              column(1, icon(
                name = "arrow-right", 
                lib = "font-awesome", 
                style = "color: black; font-size: 30px;")),
              
              # Models check
              column(1, models_icon[[1]]), 
              column(1, icon(
                name = "arrow-right", 
                lib = "font-awesome", 
                style = "color: black; font-size: 30px;")),
              
              # Policy check
              column(1, policy_icon[[1]])
            )
          ),
          
          br(),
          br(),
          
          if (!is_empty(load_icon[[2]])) {
            p(load_icon[[2]], style = "color: #F5CF27;")
          },
          
          easyClose = FALSE,
          
          footer = tagList(
            modalButton("Close")
          ))
      )
      
      # # Run through checks for each section in project
      # q_test <- quietly_test(checklist)
      # project_checklist <- q_test(project_name(), project_data())
      #
      # # Store output from checklist() in a reactive
      # rv_project_checklist(project_checklist)
      #
      # # Overall status - TRUE if all checks have passed
      # checklist_status <- all(vapply(project_checklist, function(x) x$pass, logical(1)))
      
    })
  })
} 

# # Upload data check
# column(1, icon(name="file-arrow-up", lib="font-awesome", style="color: green; font-size: 30px;")),
# column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
# 
# # QAQC check
# column(1, pass_icon('qaqc', rv_project_checklist())),
# column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
# 
# # Format data check
# column(1, icon(name="file-lines", class="fa-solid", lib="font-awesome", style="color: #FFBF00; font-size: 30px;")),
# column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
# 
# # Modeling check
# column(1, icon(name="gears", lib="font-awesome", style="color: black; font-size: 30px;")),
# column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
# 
# # Policy check
# column(1, icon(name="fish-fins", lib="font-awesome", style="color: black; font-size: 30px;"))