---
title: "Introduction to FishSET"
author: "Melanie Harsch"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to FishSET}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The Spatial Economics Toolbox for Fisheries (FishSET) is a set of statistical programming and data management tools developed to achieve the following goals:
 
  1. Standardize data management and organization. 
 
  1. Provide easily accessible tools to enable location choice models to provide input to the management of key fisheries.
 
  1. Organize statistical code so that predictions of fisher behavior developed by the field’s leading innovators can be incorporated and transparent to all users.
 
The FishSET package provides functions for:
  * Data management
  * Data Analysis
  * Mapping
  * Statistical Modeling

## Data
There are 5 types of data files that can be imported into FishSET

File Type           Description          
----------------   ------------------------
Main data           Required file that contains the main data for the model 
Port data           Required file with the latitude and longitude locations of ports
Gridded data        Optional file that contains any variable to connect to the data set that varies by two dimensions, one of which must be the map grid 
Auxilliary data     Optional file that contains additional data to link to the data set
Seaonal data        Optional file that contains additional data on fishery seasons that can be linked to the main data set

FishSET will accept several data formats including:
  * csv files
  * txt files
  * json files
  * matlab files  
  * shape files
  * spss files
  * R files 

Use the read.dat function to read in these files.

### Data import and saving functions
Data are saved in the sqlite database, fishset_db.

Data can be imported and saved into the database using:
 * read_dat  Import data into R from several formats
 * load_maindata   Saves the main dataset into the database and generates the main data table information table. Both tables are saved in the fishset database. 
 * load_port  Checks that latitude and longitude and port identification are defined. Saves the table in the fishset database. 
 * load_aux   Checks that latitude and longitude are defined. Saves the table in the fishset database. 
 * load_seasonal   Checks that a date variable is defined. Saves the table in the fishset database. 
 
 Once data are saved in the fishset_db database, they can be accessed and viewed using:
 * tables_database()   View tables in the fishset_db database
 * table_fields(x)     View fields in the table (here table x)
 * table_view(x)       View table x from the fishset_db database
 

### Data management functions
Data management functions provide tools for
visualizing the data:  
   * summary_stats
Checking for outliers:  
 * outlier_check
 * outlier_table
 * outlier_plot
 * outlier_remove
Checking for NaNs 
 * nan_filter
 * nan_idenitfy
Further filtering
 * filter_data
 * filter_dat 
Running multiple functions
 * data_check
 * data_verification
 * check_model_data



The data_check function calls several data management functions including, summary_stats, nan_identify, outlier_table, outlier_plot, and data_verification. The nan_identify and two outlier functions are meant to aid in identifying whether outlying points occur in the dataset and identify the occurrence of NaNs in the dataset. Outliers can be removed with outlier_remove. NaNs can be removed with nan_filter.

Further filtering of the data can be accomplished using the filter_data and filter_dat functions. The filter_data functions allows users define and save filter functions as a table. 

dataframe           vector               FilterFunction        
----------------   -----------------     -----------------------
MainDataTable      "PORT_CODE"           PORT_CODE==1
MainDataTable      "TRIP_START"          TRIP_START >= 2011-02-01
Port data          "LATITUDE"            LATITUDE<57

The filter functions can then be called and applied to the data using the filter_dat function.

The data_verification function runs more general checks on the dataset at the time that the data is loaded into FishSET, including that all columnn names in the dataset are unique, that specialized variables have been identified in the index dataset, that no columns in the dataset are empty, that units are defined and recognized, that each row is a unique choice occurrence at the haul or trip level, and that data for either lat/long or fishing area are included. 

The check_model_data function checks that the dataset meets several requirements, including no NA's and INF values in the data, that each row is a unique occurrence at the haul or trip level. 

It is recommended that users begin by running the data_check. It is recommended to run the check_model_data function before moving on to the modeling functions. There are several data creation functions that users may which to run before moving on to generating models.

### Data creation functions
Several functions exist that allow users to modify or create vectors and matrices. These functions are useful to ensure date vectors are in the correct format, to generate rate variables (such as catch/hours fished), calculating more complex variables such as trip distance, and adding variance to confidential data.

Functions that modify vectors focus on 
  * temp_mod: transforms a date variable into desired units (year, month, month/day, minutes)
  * set_quants: generating a coded variable based on the quantiles of selected variable. This function is especially useful for handling confidential data.
    
Functions to create nominal ID variables.
  * ID_var: creates a nominal variable to indicate distinct hauls or trips
  * create_seasonal_ID: creates a fishery season identifier (TRUE/FALSE)

Create vectors
  * create_var_num: creates a new numeric variable based on defined arithmetic function of two variables ()
  * create_var_temp: calculates the duration of time between two temporal variables based on defined time format.
  * cpue: creates catch per unit effort variable
  * dummy_var: creates a vector of TRUE or FALSE the length of the dataset 
  * dummy_matrix: creates a matrix with same dimensions at the dataset filled with TRUE or FALSE


  * haul_to_trip
    Collapse the dataframe from haul to trip.

   
  * trip_distance
    Summation of distance across a trip based on choices by the user for starting and ending ports, and hauls in between.

Before moving on, it is recommended that users run the check_model_data function to check for further data issues in existing and created data.

## Mapping functions

Mapping functions are in development

## Modeling functions
FishSET requires two sets for modeling, 1) create a model design file and 2) run model with selected likelihood function and parameters

###Create model desing functions
  The following functions are called indirectly
    * assignment_column:  assigns each observation (row) in the dataset to a zone based on Latitude and Longitude
    * find_centroid: returns the center of a zone or area based on set of latitude and longitudes 
  
  The following functions should be called in the order listed: 
    * create_alternative_choice: creates the alternative choice matrix. Calls the assignment_column and find_centroid functions
    * create_expectations: create an expectation of catch for alternative choices that are added to the model design file
    * make_model_design: creates the model design file that contains data to be used in the model runs

###Run model functions  
  The following funcitons are called indirectly
    * shift_sort_x:  shifts choices so that the chosen zone will be automatically the first one
    * create_logit_input: creates a data matrix that is consistent with the built in model forms
    
  Multiple likelihood function have been written. Users can also write their own likelihood functions.
    * logit_c
    * logit_avgcat
    * epm_normal
    * epm_lognormal
    * epm_weibull
    
  Running models
    *discrete_fish_subroutine: Runs model based on data designed in make_model_design and defined likelihood function.
    
  Viewing 
    * select_model: open an interactive table displaying model fit and model comparison measures


