# =================================================================================================
# File: checklist_module.R
# Description: A reusable Shiny module for running progress checks for FishSET projects
# Authors: Paul Carvalho, Anna Abelman
# Date: 4/9/2025
# =================================================================================================

# Module UI: checklist
# Parameters:
# - id: Module namespace identifier (req for all Shiny modules)
# Returns: An action button that triggers the checklist() function and displays UI for project progress
checklist_ui <- function(id){
   actionButton(NS(id, "checklist_btn"), "Check progress", class = "btn-primary") # action button to trigger progress checklist popup
}


# Module server: checklist
# Parameters:
# - id: Module namespace identifier (req for all Shiny modules)
# - project_name: reactive that contains project name as chr
# - project_data: reactive that contains a list of model design elements (e.g., model name, likelihood, etc.)
# Returns: a showModal() popup that displays progress for current project
checklist_server <- function(id, project_name, project_data){
   moduleServer(id, function(input, output, session){
      
      # Create a namespace function for UI updates
      ns <- session$ns
      
      # ===== REACTIVE VALUES =====
      
      rv_project_checklist = reactiveVal(NULL) # Output from checklist()
      
      # ===== FUNCTIONS =====
      
      # Icon wrapper
      # Description: Wrapper function for icon
      # Parameters: 
      # - icon_name: character representing the name of the icon
      # - icon_color: character representing the name of the color for the icon
      # Returns: an icon object
      icon_wrapper <- function(icon_name, icon_color) {
         icon(name=icon_name, lib="font-awesome", style=paste0("color: ", icon_color, "; font-size: 30px;"))
      }
      
      # Pass icon
      # Description: This function returns icons to be displayed in the progress check popup, and sets color based on 
      #              pass/fail of checklist tests.
      # Parameters:
      # - type: character representing which list element to evaluate from the output generated by the checklist() function
      # - project_checklist: list generated by the checklist() function that contains checkpoints and status
      # Returns: an icon object to be displayed in the progress check popup
      pass_icon <- function(type, project_checklist) {s
         # QAQC
         if(type=='qaqc'){
            if(project_checklist[[type]]$pass){
               tmp_icon <- icon_wrapper('magnifying-glass-chart', 'green')
            } else {
               tmp_icon <- icon_wrapper('magnifying-glass-chart', 'black')
            }
         }
         return(tmp_icon)
      }
      
      # ===== OUTPUTS =====
      
      # Display progress check popup for current project
      observeEvent(input$checklist_btn, {
         # Run through checks for each section in project
         q_test <- quietly_test(checklist)
         project_checklist <- q_test(project_name(), project_data())
         
         # Store output from checklist() in a reactive
         rv_project_checklist(project_checklist)
         
         # Overall status - TRUE if all checks have passed
         checklist_status <- all(vapply(project_checklist, function(x) x$pass, logical(1)))
         
         # Display progress check UI
         showModal(modalDialog(title = "FishSET Progress",
                               uiOutput(session$ns("checklist_diagram")), # dynamic UI placeholder
                               easyClose = FALSE, 
                               footer = tagList(
                                  modalButton("Close")
                               ))
         )
      })
      
      # Dynamically render the progress diagram
      output$checklist_diagram <- renderUI({
         tags$div(
            # TEMPORARY MESSAGE TO THE USER
            tags$strong("THIS FEATURE IS UNDER DEVELOPMENT AND DOES NOT REFLECT CURRENT PROJECT STATUS"),
            
            tags$br(),
            tags$br(),
            
            fluidRow(
               # Upload data check
               column(1, icon(name="file-arrow-up", lib="font-awesome", style="color: green; font-size: 30px;")),
               column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
               
               # QAQC check
               column(1, pass_icon('qaqc', rv_project_checklist())),
               column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
               
               # Format data check
               column(1, icon(name="file-lines", class="fa-solid", lib="font-awesome", style="color: #FFBF00; font-size: 30px;")),
               column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
               
               # Modeling check
               column(1, icon(name="gears", lib="font-awesome", style="color: black; font-size: 30px;")),
               column(1, icon(name="arrow-right", lib="font-awesome", style="color: black; font-size: 30px;")),
               
               # Policy check
               column(1, icon(name="fish-fins", lib="font-awesome", style="color: black; font-size: 30px;"))
            ),
         )
      })
   })
} 
