# -------------------------------------------------------------------------------------------------
# File: test-format_model_data.R
# Purpose: To provide unit tests for the format_model_data() function.
# Description: This script uses the 'testthat' framework to validate the behavior of 
#              format_model_data. It mocks internal FishSET database interactions to test
#              the reshaping logic, distance calculation integration, expectation merging,
#              and imputation handling in isolation.
#
# Scenarios tested:
#   - Basic reshaping (long format creation) using the cross_join logic.
#   - Correct identification of the 'chosen' alternative.
#   - Integration of distance matrices.
#   - Handling of missing data (NAs) via imputation (Mean/Mode) and removal.
#   - Input validation (error handling).
#   - Merging of expectation matrices.
#
# -------------------------------------------------------------------------------------------------

# Test Data Setup ---------------------------------------------------------------------------------
# Mock Main Data
main_data <- data.frame(
  unique_row_id = c("1", "2", "3"),
  ZoneID = c("A", "B", "A"), 
  other_var = c(10, 20, 30)
)

# Mock AltMatrix 
alt_matrix <- list(
  greaterNZ = c("A", "B"), 
  alt_var = "nearest point",
  occasion = "trip",
  occasion_var = "unique_row_id",
  dataZoneTrue = rep(1, 3),
  choice = c("A", "B", "A"),
  zoneID = "ZoneID",
  zone_cent = NULL,
  fish_cent = NULL,
  altChoiceUnits = "km",
  spat = NULL, 
  spatID = NULL
)

# The unserialize_table returns a LIST of these matrices
alt_matrix_list <- list(
  test_alt_1 = alt_matrix
)

# Mock Distance Matrix Output
dist_mat_mock <- matrix(
  c(5, 10,  
    15, 20, 
    25, 30),
  nrow = 3, byrow = TRUE
)
colnames(dist_mat_mock) <- c("A", "B")
rownames(dist_mat_mock) <- c("1", "2", "3")
dist_out_mock <- list(dist_matrix = dist_mat_mock)

# Mock Expectation List
exp_list_mock <- list(
  catch_exp = matrix(c(100, 200, 300, 400, 500, 600), nrow = 3, byrow = TRUE,
                     dimnames = list(NULL, c("A", "B")))
)

# Environment and mock setup ----------------------------------------------------------------------
# Preserve original functions to prevent bleeding
orig_functions <- list(
  table_exists = getFromNamespace("table_exists", "FishSET"),
  table_view   = getFromNamespace("table_view", "FishSET"),
  unserialize_table = getFromNamespace("unserialize_table", "FishSET"),
  create_dist_matrix = getFromNamespace("create_dist_matrix", "FishSET"),
  column_check = getFromNamespace("column_check", "FishSET"),
  log_call = getFromNamespace("log_call", "FishSET"),
  locdatabase = getFromNamespace("locdatabase", "FishSET"),
  data_pull = getFromNamespace("data_pull", "FishSET")
)

clean_mock_table_view <- function(table_name, project) {
  if (grepl("MainDataTable", table_name)) return(main_data)
  if (grepl("AuxTable", table_name)) return(data.frame(key="1", aux_val=99))
  return(NULL)
}
clean_mock_create_dist <- function(...) return(dist_out_mock)
clean_mock_table_exists <- function(table_name, project) return(FALSE)
clean_mock_unserialize <- function(table_name, project) {
  if (grepl("AltMatrix", table_name)) return(alt_matrix_list)
  if (grepl("ExpectedCatch", table_name)) return(exp_list_mock)
  return(list())
}
clean_mock_col_check <- function(...) return(TRUE)
clean_mock_log <- function(...) invisible(NULL)
clean_mock_locdb <- function(...) return(":memory:")
clean_mock_data_pull <- function(...) return(list(dat="x", dataset=NULL))

setup_mocks <- function() {
  assignInNamespace("table_exists", clean_mock_table_exists, ns = "FishSET")
  assignInNamespace("table_view", clean_mock_table_view, ns = "FishSET")
  assignInNamespace("unserialize_table", clean_mock_unserialize, ns = "FishSET")
  assignInNamespace("create_dist_matrix", clean_mock_create_dist, ns = "FishSET")
  assignInNamespace("column_check", clean_mock_col_check, ns = "FishSET")
  assignInNamespace("log_call", clean_mock_log, ns = "FishSET")
  assignInNamespace("locdatabase", clean_mock_locdb, ns = "FishSET")
  assignInNamespace("data_pull", clean_mock_data_pull, ns = "FishSET")
}

restore_mocks <- function() {
  assignInNamespace("table_exists", orig_functions$table_exists, ns = "FishSET")
  assignInNamespace("table_view", orig_functions$table_view, ns = "FishSET")
  assignInNamespace("unserialize_table", orig_functions$unserialize_table, ns = "FishSET")
  assignInNamespace("create_dist_matrix", orig_functions$create_dist_matrix, ns = "FishSET")
  assignInNamespace("column_check", orig_functions$column_check, ns = "FishSET")
  assignInNamespace("log_call", orig_functions$log_call, ns = "FishSET")
  assignInNamespace("locdatabase", orig_functions$locdatabase, ns = "FishSET")
  assignInNamespace("data_pull", orig_functions$data_pull, ns = "FishSET")
}

# Helper to read the flat file generated by the function (Handles both QS2 and RDS!)
read_fmd_output <- function(project_name, base_dir) {
  fd_dir <- file.path(base_dir, project_name, "Models", "FormattedData")
  qs2_file <- file.path(fd_dir, paste0(project_name, "LongFormatData.qs2"))
  rds_file <- file.path(fd_dir, paste0(project_name, "LongFormatData.rds"))
  
  if (file.exists(qs2_file) && requireNamespace("qs2", quietly = TRUE)) {
    return(qs2::qs_read(qs2_file))
  } else if (file.exists(rds_file)) {
    return(readRDS(rds_file))
  }
  stop(paste("Formatted data file not found in directory:", fd_dir))
}

# Reshape and assign choices correctly ------------------------------------------------------------
test_that("format_model_data reshapes and assigns choices correctly", {
  setup_mocks()
  
  test_base_dir <- normalizePath(file.path(tempdir(), "FishSET_FMD_Tests"), 
                                 winslash = "/", 
                                 mustWork = FALSE)
  dir.create(file.path(test_base_dir, "TEST_PROJ_RESHAPE", "src"), 
             recursive = TRUE, 
             showWarnings = FALSE)
  
  old_opts <- options(test_folder_path = test_base_dir)
  on.exit({
    options(old_opts)
    restore_mocks()
  }, add = TRUE)
  
  suppressMessages(
    format_model_data(project = "TEST_PROJ_RESHAPE", 
                      name = "TEST_MODEL", 
                      alt_name = "test_alt_1",
                      zone_id = "ZoneID", 
                      unique_obs_id = "unique_row_id", 
                      select_vars = c("other_var"),
                      distance = TRUE, 
                      distance_units = "mi")  
  )
  
  df_out <- read_fmd_output("TEST_PROJ_RESHAPE", test_base_dir)$TEST_MODEL
  expect_equal(nrow(df_out), 6)
  expect_true(all(c("distance", "chosen", "other_var", "ZoneID") %in% names(df_out)))
})


# Test imputation ---------------------------------------------------------------------------------
test_that("format_model_data handles imputation correctly", {
  setup_mocks()
  test_base_dir <- normalizePath(file.path(tempdir(), "FishSET_FMD_Tests"), 
                                 winslash = "/", 
                                 mustWork = FALSE)
  dir.create(file.path(test_base_dir, "TEST_PROJ_MEAN", "src"), 
             recursive = TRUE, 
             showWarnings = FALSE)
  dir.create(file.path(test_base_dir, "TEST_PROJ_REM", "src"), 
             recursive = TRUE, 
             showWarnings = FALSE)
  
  old_opts <- options(test_folder_path = test_base_dir)
  on.exit({
    options(old_opts)
    restore_mocks()
  }, add = TRUE)
  
  # Mean Imputation Test
  main_data_na <- main_data
  main_data_na$other_var[1] <- NA
  assignInNamespace("table_view", 
                    function(t, p) if(grepl("Main", t)) main_data_na else NULL, ns = "FishSET")
  
  suppressMessages(
    format_model_data(project = "TEST_PROJ_MEAN", 
                      name = "TEST_MEAN", 
                      alt_name = "test_alt_1",
                      zone_id = "ZoneID", 
                      unique_obs_id = "unique_row_id", 
                      select_vars = c("other_var"),
                      distance = FALSE, 
                      impute = "mean")  
  )
  
  
  df_mean <- read_fmd_output("TEST_PROJ_MEAN", test_base_dir)$TEST_MEAN
  expect_true(all(df_mean$other_var[df_mean$unique_row_id == "1"] == 25))
  
  # Remove Imputation Test
  assignInNamespace("table_view", clean_mock_table_view, ns = "FishSET")
  dist_mat_na <- dist_mat_mock; dist_mat_na[1, "A"] <- NA
  assignInNamespace("create_dist_matrix", 
                    function(...) list(dist_matrix = dist_mat_na), ns = "FishSET")
  
  suppressMessages(
    format_model_data(project = "TEST_PROJ_REM", 
                      name = "TEST_REMOVE", 
                      alt_name = "test_alt_1",
                      zone_id = "ZoneID", 
                      unique_obs_id = "unique_row_id", 
                      select_vars = c("other_var"),
                      distance = TRUE, 
                      distance_units = "mi", 
                      impute = "remove")  
  )
  
  df_rem <- read_fmd_output("TEST_PROJ_REM", test_base_dir)$TEST_REMOVE
  expect_equal(nrow(df_rem), 3)
})


# Test merging expectations -----------------------------------------------------------------------
test_that("format_model_data merges expectations correctly", {
  setup_mocks()
  test_base_dir <- normalizePath(file.path(tempdir(), "FishSET_FMD_Tests"), 
                                 winslash = "/", 
                                 mustWork = FALSE)
  dir.create(file.path(test_base_dir, "TEST_PROJ_EXP", "src"), 
             recursive = TRUE, 
             showWarnings = FALSE)
  
  old_opts <- options(test_folder_path = test_base_dir)
  on.exit({
    options(old_opts)
    restore_mocks()
  }, add = TRUE)
  
  suppressMessages(
    format_model_data(project = "TEST_PROJ_EXP", 
                      name = "TEST_EXP", 
                      alt_name = "test_alt_1",
                      zone_id = "ZoneID", 
                      unique_obs_id = "unique_row_id", 
                      distance = FALSE, 
                      expectations = c("catch_exp"))  
  )
  
  df_out <- read_fmd_output("TEST_PROJ_EXP", test_base_dir)$TEST_EXP
  expect_true("catch_exp" %in% names(df_out))
})


# Test model fail for invalid inputs --------------------------------------------------------------
test_that("format_model_data fails fast on invalid inputs", {
  setup_mocks()
  test_base_dir <- normalizePath(file.path(tempdir(), "FishSET_FMD_Tests"), 
                                 winslash = "/", 
                                 mustWork = FALSE)
  
  old_opts <- options(test_folder_path = test_base_dir)
  on.exit({
    options(old_opts)
    restore_mocks()
  }, add = TRUE)
  
  expect_error(
    format_model_data(project = "TEST_PROJ_FAIL", 
                      name = "FAIL", 
                      alt_name = "test_alt_1", 
                      zone_id = "ZoneID", 
                      unique_obs_id = "unique_row_id", 
                      distance = FALSE, 
                      impute = "magic_wand"),
    "Impute method must be one of"
  )
})