---
title: "Using FishSET in the RConsole"
site: "bookdown::bookdown_site"
output:
   bookdown::pdf_book:
    keep_tex: yes
---

# Welcome to FishSET

This chapter details the goals of FishSET, outlines the different chapters of this document, and provides instructions for installing FishSET.

## Introduction


The Spatial Economics Toolbox for Fisheries (FishSET) is a set of statistical programming and data management tools developed to achieve the following goals:
 
  1. Standardize data management and organization. 
  
  1. Provide easily accessible tools to enable location choice models to provide input to the management of key fisheries.
  
  1. Organize statistical code so that predictions of fisher behavior developed by the field’s leading innovators can be incorporated and transparent to all users.


The FishSET package provides functions for:

* Data management
* Data analysis
* Visualizing data
* Mapping fishing effort
* Statistical modeling of fisher behavior
* Policy comparisons
* Reproducibility
  
FishSET is designed for reproducibility. 

* All input and output are stored in the FishSETFolder directory and organized by projects.
* Data is stored in *fishset_db* SQLite databases, the FishSET database. 
* Function calls and notes are stored in a *src* folder.
* Output (plots, table, messages, notes) are saved in an *Output* folder. 

This document contains a brief description of the FishSET functions and assumes familiarity with R. 
If you are unfamiliar with R, we recommended running FishSET functions in the FishSET GUI rather than the RConsole. See the [FishSET GUI vignette](FishSET_GUI.html) for more information.

A more detailed manual is available at the ***[FishSET GitHub site](WEBSITE URL)***. 

## Getting started
If not all ready installed, install [R](https://cloud.r-project.org/ "Download R") and [RStudio](https://www.rstudio.com/products/rstudio/download/#download "Download RStudio").
RStudio is not required but is recommended.  

To install the FishSET package, all users need the `devtools` package and Windows users must install [Rtools](https://cran.r-project.org/bin/windows/Rtools/ "Download Rtools"). 

Install devtools (required)
: `install.packages("devtools")`   
 `library(devtools)`


FishSET is provided as a compressed file that can be installed directly from the FishSET GitHUB site (recommended) or 
from a locally saved file location. 

Install FishSET  
: To install FishSET from GitHUB  
  `devtools::install_github("name/FishSET")`     

: To install FishSET from local file directory 
    `devtools::install_local("PATH/TO/Directory/Containing/FishSET")`  
    `library(FishSET)`
    
Dependencies should be automatically installed. This can take awhile.

For more detailed directions and images, see the [Installing R and RStudio](https://docs.google.com/document/d/1dzXsVt5iWcAQooDDXRJ3XyMoqnSmpZOqirU_f_PnQUM/edit#heading=h.1fob9te "Installing R and RStudio") and [Installing FishSET](https://docs.google.com/document/d/1dzXsVt5iWcAQooDDXRJ3XyMoqnSmpZOqirU_f_PnQUM/edit#heading=h.h8fxguvqf0mn "Installing FishSET") section of the FishSET Manual.
	  
##Using FishSET
FishSET functions can be called in the R console or through the FishSET Graphical User Interface (FishSET GUI). This document details how to use FishSET in the R Console. The FishSET GUI is detailed in the *FishSET GUI* vignette. Background and greater detail on functions can be found in the [FishSET Help Manual](https://docs.google.com/document/d/1dzXsVt5iWcAQooDDXRJ3XyMoqnSmpZOqirU_f_PnQUM/edit?usp=sharing "Help Manual").

## What is a project?
Data and output are organized into *projects*. A `project` is a unique identifier for a set of data and analyses. `Project` names can be any set of alpha-numeric characters. For instance, a `project` can be called *pollock* or *pollock2020*. All input and output are saved to a directory with the name of the `project` within the FishSETFolder directory.

## Chapter overview
### Chapter 2 [Data]
This chapter goes over the types of data used in FishSET and how to load the data into FishSET. The chapter then outlines functions for conducting basic data quality checks and fixing any issues that arise.

### Chapter 3 [Data Exploration]
This chapter goes over the functions to visualize and explore the data. 

### Chapter 4 [Spatial Functions]
This chapter outlines the numerous functions related to visualizing the data spatially and generating plots of the spatial distribution of the data.

### Chapter 5 [Creating and Modifying Data]
This chapter outlines the functions to generate new variables, such as catch per unit effort, or modify existing variables, such as extracting year from a date variable.

### Chapter 6 [Modeling Functions]
This chapter goes over the steps required to generate the data used in the models, define the models, run the models, and compare output.

### Chapter 7 [Policy and Welfare Analysis]
The chapter goes over how to define policy scenarios and run welfare analyses.

### Chapter 8 [Reporting]
This chapter goes over how to open and use the report template.

