filter_table <- function(dat, project, x, exp) {
  #'  Define and store filter expressions
  #'
  #' @param dat Primary data containing information on hauls or trips.
  #'   Table in the FishSET database contains the string 'MainDataTable'.
  #' @param project String, name of project.
  #' @param x Variable in \code{dat} over which filter will be applied.
  #' @param exp Filter expression. Should take on the form of \code{"x<100"} or \code{"is.na(x) == F"}.
  #' @importFrom utils head read.csv write.csv
  #' @importFrom DBI dbConnect dbWriteTable dbDisconnect
  #' @keywords filter, subset
  #' @export filter_table
  #' @return  Filter expressions saved as a table to the FishSET database.
  #' @details This function allows users to define and store data filter expressions which can then be applied to the data.
  #' The filter table will be saved in the FishSET database under the \code{project} name and `filterTable`.
  #' The new filter functions are added each time the function is run and the table is  automatically updated in the
  #' FishSET database. The function call will be logged in the log file.
  #' @examples
  #' \dontrun{
  #' filter_table(pcodMainDataTable, 'pcod', 'PERFORMANCE_Code','PERFORMANCE_Code==1')
  #' }
  #'

  # Call in datasets
  out <- data_pull(dat, project)
  dataset <- out$dataset
  dat <- parse_data_name(dat, "main", project)
  
  if (table_exists(paste0(project, "FilterTable"), project) == F) {
    filterTable <- data.frame(dataframe = NA, vector = NA, FilterFunction = NA)
    filterTable[1, ] <- c(dat, x, exp)
  } else {
    filterTable <- table_view(paste0(project, "FilterTable"), project)
    filterTable <- rbind(filterTable, c(dat, x, exp))
  }


  fishset_db <- suppressWarnings(DBI::dbConnect(RSQLite::SQLite(), locdatabase(project = project)))
  on.exit(DBI::dbDisconnect(fishset_db), add = TRUE)
  
  DBI::dbWriteTable(fishset_db, paste0(project, "FilterTable"), filterTable, overwrite = TRUE)
  cat("Table saved to fishset_db database")

  filter_data_function <- list()
  filter_data_function$functionID <- "filter_table"
  filter_data_function$args <- list(dat, project, x, exp)
  filter_data_function$msg <- filterTable
  log_call(project, filter_data_function)

  save_table(filterTable, project, "filter_table")

  print(filterTable)
}



filter_dat <- function(dat, project, exp, filterTable = NULL) {
  #' Remove rows based on filter expressions defined in 'filterTable'
  #'
  #' @param dat Primary data containing information on hauls or trips. Table in the FishSET database contains the string 'MainDataTable'.
  #' @param project Project name. 
  #' @param exp How to filter. May be a row in the filter table generated by \code{\link{filter_table}} that contains a filter
  #' expression or the filter expression to apply to the data. If the filter expression is supplied, it should take on the form of \code{"x<100"} or \code{"is.na(x) == F"}.
  #' @param filterTable Name of filter table in FishSET database. Name should contain the phrase 'filterTable'.
  #' @keywords filter, subset
  #' @export filter_dat
  #' @return Filtered data frame
  #' @details Filter data frame based on a predefined filter expression from \code{\link{filter_table}} or a filter expression.
  #' We recommend creating a filter table using \code{\link{filter_table}} so that filter expressions are stored and easily
  #' accessed in the future.
  #' @examples
  #' \dontrun{
  #' newdat <- filter_dat(pcodMainDataTable, 'pollock', exp = 3, filterTable = 'pcodfilterTable01012011')
  #' newdat <- filter_dat(pcodMainDataTable, 'pollock', exp = 'PERFORMANCE_Code==1', filteTable = NULL)
  #' }
  #'

  # Call in datasets
  out <- data_pull(dat, project)
  dataset <- out$dataset
  dat <- parse_data_name(dat, "main", project)
  
  # NaNs only occurs on Numeric Variables
  if (!is.null(filterTable) && table_exists(filterTable, project)) {
    
    filterTab <- table_view(filterTable, project)

    cat("The entire row will be removed from the dataframe.")
    dataset <- subset(dataset, eval(parse(text = filterTab[exp, 3])))
    
  } else {
    
    dataset <- subset(dataset, eval(parse(text = exp)))
  }

  filter_dat_function <- list()
  filter_dat_function$functionID <- "filter_dat"
  filter_dat_function$args <- list(dat, project, exp, filterTable)
  filter_dat_function$output <- dat
  filter_dat_function$msg <- paste("Rows have been removed based on", exp)
  log_call(project, filter_dat_function)

  return(dataset)
}
