# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_moving_avg <- function(unique_dates, unique_groups, obs_dates, obs_groups, obs_values, window_size, lag) {
    .Call(`_FishSET_calculate_moving_avg`, unique_dates, unique_groups, obs_dates, obs_groups, obs_values, window_size, lag)
}

shift_sort_xcpp <- function(x, ch, y, distance, alts, ab) {
    .Call(`_FishSET_shift_sort_xcpp`, x, ch, y, distance, alts, ab)
}

