#' Run Policy and Data Simulations
#'
#' Simulates the impact of policy changes (e.g., area closures) or changes in exogenous 
#' variables (e.g., fuel prices, expected catch) on redistributed fishing effort and 
#' economic welfare.
#'
#' @param project Character. Name of the project.
#' @param mod_name Character. Name of the fitted model to use for the simulation.
#' @param closures List (Optional). A list of closure scenarios generated by zone_closure().
#' @param data_modifiers List (Optional). A named list of new data vectors to inject into the 
#'   model. Names must match variables in the model's design matrix or price vector.
#' @param betadraws Integer. Number of multivariate normal draws for the simulation. 
#'   Default is 1000.
#' @param marg_util_income Character. For standard/zonal logit models: Name of the coefficient 
#'   to use as the marginal utility of income to calculate welfare in dollars.
#' @param income_cost Logical. Default FALSE. Set to TRUE if the `marg_util_income` parameter 
#'   represents a cost (flips the sign of the coefficient).
#'
#' @return An object of class `fishset_policy` containing simulation results.
#' @export
#' @importFrom DBI dbConnect dbDisconnect dbExecute dbGetQuery
#' @importFrom RSQLite SQLite
#' @importFrom MASS mvrnorm

run_simulation <- function(project,
                           mod_name,
                           closures = NULL,
                           data_modifiers = NULL,
                           betadraws = 500,
                           marg_util_income = NULL,
                           income_cost = FALSE) {
  
  # Setup and database connection -----------------------------------------------------------------
  fishset_db <- DBI::dbConnect(RSQLite::SQLite(), locdatabase(project = project))
  on.exit(DBI::dbDisconnect(fishset_db), add = TRUE)
  
  # Load model design (X matrices, epm components, scalers)
  paths <- file.path(locproject(), project, "Models", "ModelDesigns", 
                     c(paste0(mod_name, ".qs2"), paste0(mod_name, ".rds")))
  found_path <- paths[file.exists(paths)][1]
  if (is.na(found_path)) stop(paste("Model design", mod_name, "not found. Run fishset_design()."))
  
  if (grepl("\\.qs2$", found_path)) {
    design <- qs2::qs_read(found_path)
  } else {
    design <- readRDS(found_path)
  }
  
  # Load Fitted Model
  fit_list <- unserialize_table(paste0(project, "ModelFit"), project)
  fit_name <- paste0(mod_name, "_fit")
  if (!(fit_name %in% names(fit_list))) {
    stop(paste("Model fit", fit_name, "not found. Run fishset_fit() first."))
  }
  fit <- fit_list[[fit_name]]

  # Delete the full fit_list
  rm(fit_list)
  
  is_epm <- isTRUE(design$epm$is_epm)
  N_obs <- design$settings$N_obs
  J_alts <- design$settings$J_alts
  
  # Auto-detect distribution for EPM
  if (is_epm) {
    coef_names <- names(fit$coefficients)
    if (any(grepl("Sigma_Catch_", coef_names))) {
      distribution <- "normal"
    } else if (any(grepl("Sdlog_Catch_", coef_names))) {
      distribution <- "lognormal"
    } else if (any(grepl("Shape_Catch_", coef_names))) {
      distribution <- "weibull"
    } else {
      stop("Could not infer EPM distribution from model fit coefficients.")
    }
  } else {
    distribution <- "logit"
  }
  
  # Extract data and parameter draws --------------------------------------------------------------
  # Create base matrices
  X_base <- design$X
  if (is_epm) {
    X_catch_base <- design$epm$X_catch
    price_base <- design$epm$price_vec
    
    # EPMs split the design matrix
    cost_cols <- setdiff(colnames(X_base), colnames(X_catch_base))
    X_cost_base <- X_base[, cost_cols, drop = FALSE]
  }
  
  # Check Hessian for valid covariance matrix
  hess <- fit$diagnostics$hessian
  if (is.null(hess) || any(is.na(hess))) {
    stop("Invalid Hessian matrix in model fit. Cannot generate parameter draws.")
  }
  
  cov_mat <- tryCatch(solve(hess), error = function(e) NULL)
  if (is.null(cov_mat)) stop("Hessian matrix is not invertible (not positive definite).")
  
  # Draw parameters from Multivariate Normal
  beta_draws <- MASS::mvrnorm(n = betadraws, mu = fit$opt$par, Sigma = cov_mat)
  colnames(beta_draws) <- names(fit$opt$par)
  
  # Apply data modifiers (counterfactual X) -------------------------------------------------------
  X_new <- X_base
  if (is_epm) {
    X_catch_new <- X_catch_base
    X_cost_new <- X_new[, cost_cols, drop = FALSE]
    price_new <- price_base

  }
  
  if (!is.null(data_modifiers)) {
    for (var_name in names(data_modifiers)) {
      new_vec <- data_modifiers[[var_name]]
      
      # Helper to apply FishSET scaling
      scale_new_data <- function(vec, var, scalers) {
        if (!is.null(scalers)) {
          # Check X1/X2 scalers
          sds <- c(scalers$X1$sd, unlist(scalers$X2$sd), 
                   scalers$X1_catch$sd, unlist(scalers$X2_catch$sd))
          mus <- c(scalers$X1$mu, unlist(scalers$X2$mu), 
                   scalers$X1_catch$mu, unlist(scalers$X2_catch$mu))
          if (var %in% names(sds)) {
            vec <- (vec - mus[var]) / sds[var]
          }
        }
        return(vec)
      }
      
      # Modify standard matrix
      if (var_name %in% colnames(X_new)) {
        X_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
      }
      
      # Modify EPM matrices
      if (is_epm) {
        if (var_name %in% colnames(X_catch_new)) {
          X_catch_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
        }
        if (var_name == "price") {
          p_div <- if (!is.null(design$scalers$price_divisor)) design$scalers$price_divisor else 1
          price_new <- new_vec / p_div
        }
      }
    }
  }
  
  if (is_epm) {
    y_div <- if (!is.null(design$scalers$Y_catch_divisor)) design$scalers$Y_catch_divisor else 1
    p_div <- if (!is.null(design$scalers$price_divisor)) design$scalers$price_divisor else 1
    epm_welfare_multiplier <- y_div * p_div
  }
  
  # Load closures from YAML -----------------------------------------------------------------------
  if (!is.null(closures)) {
    yaml_file <- paste0(locoutput(project), pull_output(project, type = "zone", fun = "closures"))
    
    if (utils::file_test("-f", yaml_file)) {
      all_closures <- yaml::read_yaml(yaml_file)
      scenarios <- all_closures[vapply(all_closures, 
                                       function(x) x$scenario %in% unlist(closures), logical(1))]
      
      if (length(scenarios) == 0) {
        available_scens <- vapply(all_closures, function(x) x$scenario, character(1))
        stop(paste0("None of the specified scenario names in 'closures' were found in ",
                    "the YAML file.\n Available scenarios are: '", 
                    paste(available_scens, collapse = "', '"), "'"), call. = FALSE)
      }
    } else {
      stop("No policy scenario YAML file found. Run the zone_closure() function first.")
    }
    
  } else {
    scenarios <- list(list(scenario = "Data_Modification", zone = NULL))
  }
  
  has_mods <- !is.null(data_modifiers)
  
  # Find theta index
  if (!is_epm) {
    if (is.null(marg_util_income)) stop("Standard logit requires 'marg_util_income'.")
    theta_idx <- which(colnames(X_base) == marg_util_income)
    if (length(theta_idx) == 0) stop(paste("Coefficient", marg_util_income, "not found."))
  }
  
  results_list <- list()
  zone_vec <- as.character(design$ids$zone)
  
  # Run simulation --------------------------------------------------------------------------------
  for (scen in scenarios) {
    scenario_name <- scen$scenario
    closed_zones <- if (!is.null(scen$zone)) gsub("Zone_", "", scen$zone) else character(0)
    closed_idx <- which(zone_vec %in% closed_zones)
    
    draw_welfare <- numeric(betadraws)
    
    for (d in 1:betadraws) {
      b_d <- beta_draws[d, ]
      
      if (!is_epm) {
        V_base <- as.numeric(X_base %*% b_d)
        if (has_mods) V_new <- as.numeric(X_new %*% b_d)
        
        theta <- b_d[theta_idx]
        if (income_cost) theta <- -theta
        
        # Unscale theta if necessary
        if (!is.null(design$scalers)) {
          # Combine all potential stdev scalers
          sds <- c(design$scalers$X1$sd, unlist(design$scalers$X2$sd))
          
          # If marg_util_income was scaled, divide by its stdev
          if (marg_util_income %in% names(sds)) {
            theta <- theta / sds[marg_util_income]
          }
        }
        
        # Error check: marginal utility of income must be positive
        if (theta <= 0) {
          draw_welfare[d] <- NA
          next # skip and go to the next draw
        }
        
      } else {
        # Extract parameters
        n_c <- ncol(X_catch_base)
        n_var <- length(grep("log_sigma|Sigma|Sdlog|Shape", names(b_d), ignore.case = TRUE))
        n_u <- length(b_d) - n_c - n_var
        
        # Catch parameters are always the first n_c elements
        b_c <- b_d[1:n_c]
        
        # If X_base has columns, pull the matching parameters; otherwise leave empty
        if (n_u > 0) {
          b_u <- b_d[(n_c + 1):(n_c + n_u)]
        } else {
          b_u <- numeric(0)
        }
        
        sig_c <- exp(b_d[grep("log_sigma_c", names(b_d))])
        sig_e <- exp(b_d[grep("log_sigma_e", names(b_d))])
        
        lin_pred_base <- as.numeric(X_catch_base %*% b_c)
        if (has_mods) lin_pred_new <- as.numeric(X_catch_new %*% b_c)
        
        # Explicitly expand sig_c to match the length of the dataset
        zone_seq <- ((0:(length(lin_pred_base) - 1)) %% J_alts) + 1
        sig_c_full <- sig_c[zone_seq]
        
        if (distribution == "normal") {
          mu_catch_base <- lin_pred_base
          if (has_mods) mu_catch_new <- lin_pred_new
        } else if (distribution == "lognormal") {
          mu_catch_base <- exp(lin_pred_base + 0.5 * (sig_c^2))
          if (has_mods) mu_catch_new <- exp(lin_pred_new + 0.5 * (sig_c^2))
        } else if (distribution == "weibull") {
          mu_catch_base <- exp(lin_pred_base) * exp(lgamma(1 + 1 / sig_c))
          if (has_mods) mu_catch_new <- exp(lin_pred_new) * exp(lgamma(1 + 1 / sig_c))
        }
        
        rev_base <- price_base * mu_catch_base
        cost_base <- if (length(b_u) > 0) as.numeric(X_cost_base %*% b_u) else 0
        V_base <- (1 / sig_e) * (rev_base + cost_base)
        
        if (has_mods) {
          rev_new <- price_new * mu_catch_new
          cost_new <- if (length(b_u) > 0) as.numeric(X_cost_new %*% b_u) else 0
          V_new <- (1 / sig_e) * (rev_new + cost_new)
        }
        theta <- (1 / sig_e)
      }
      
      dim(V_base) <- c(J_alts, N_obs)
      
      # Fast Max for Base
      max_V_base <- V_base[1, ]
      for (j in 2:J_alts) {
        curr_base <- V_base[j, ]
        
        # which() filters out NA and NaN values to prevent subscript errors
        idx_base <- which(curr_base > max_V_base)
        if (length(idx_base) > 0) {
          max_V_base[idx_base] <- curr_base[idx_base]
        }
      }
      
      # Shift and exp Base
      for (j in 1:J_alts) {
        V_base[j, ] <- V_base[j, ] - max_V_base
      }
      V_base <- exp(V_base)
      
      # Base logsum (Bypass S3 Overhead)
      logsum_base <- log(.colSums(V_base, m = J_alts, n = N_obs, na.rm = FALSE)) + max_V_base
      
      if (!has_mods) {
        # Skip V_new for data modifiers
        if (length(closed_idx) > 0) {
          V_base[closed_idx] <- 0 
        }
        logsum_new <- log(.colSums(V_base, m = J_alts, n = N_obs, na.rm = FALSE)) + max_V_base
        
      } else {
        # If data changed, we must do the full CPU math for V_new
        if (length(closed_idx) > 0) V_new[closed_idx] <- -Inf
        dim(V_new) <- c(J_alts, N_obs)
        
        max_V_new <- V_new[1, ]
        for (j in 2:J_alts) {
          curr_new <- V_new[j, ]
          
          # Safely filter NAs for the counterfactual matrix
          idx_new <- which(curr_new > max_V_new)
          if (length(idx_new) > 0) {
            max_V_new[idx_new] <- curr_new[idx_new]
          }
        }
        
        for (j in 1:J_alts) {
          V_new[j, ] <- V_new[j, ] - max_V_new
        }
        
        V_new <- exp(V_new)
        logsum_new <- log(.colSums(V_new, m = J_alts, n = N_obs, na.rm = FALSE)) + max_V_new
      }
      
      welfare_diff <- (1 / theta) * (logsum_new - logsum_base)
      
      if (is_epm) {
        welfare_diff <- welfare_diff * epm_welfare_multiplier
      }
      
      draw_welfare[d] <- mean(welfare_diff, na.rm = TRUE)
    }
    
    # Store scenario summaries
    results_list[[scenario_name]] <- list(
      welfare_draws = draw_welfare,
      mean_welfare_loss = mean(draw_welfare, na.rm = TRUE),
      quantiles = quantile(draw_welfare, probs = c(0.025, 0.05, 0.5, 0.95, 0.975), na.rm = TRUE)
    )
  }
  
  # Package and save ------------------------------------------------------------------------------
  sim_obj <- list(
    model_name = mod_name,
    scenarios = results_list,
    metadata = list(
      N_obs = N_obs,
      J_alts = J_alts,
      betadraws = betadraws,
      distribution = if (is_epm) distribution else "logit",
      timestamp = Sys.time()
    )
  )
  class(sim_obj) <- "fishset_policy"
  
  table_name <- paste0(project, "PolicySimulations")
  
  # Explicitly send and clear the CREATE TABLE statement
  res_create <- DBI::dbSendStatement(fishset_db, paste("CREATE TABLE IF NOT EXISTS", 
                                                       table_name, 
                                                       "(name TEXT UNIQUE, data BLOB)"))
  DBI::dbClearResult(res_create)
  
  # Serialize the massive object
  sim_name <- paste0("Sim_", mod_name, "_", format(Sys.time(), "%Y%m%d_%H%M%S"))
  serialized_data <- list(serialize(sim_obj, NULL))
  
  # Explicitly send and clear the heavy BLOB INSERT statement
  insert_query <- paste("INSERT OR REPLACE INTO", table_name, "(name, data) VALUES (:name, :data)")
  res_insert <- DBI::dbSendStatement(fishset_db, 
                                     insert_query, 
                                     params = list(name = sim_name, data = serialized_data))
  DBI::dbClearResult(res_insert)
  
  # Force R to clean up temporary matrices and return RAM to the OS
  gc() 
  return(invisible(TRUE))
}