#' Run Policy and Data Simulations
#'
#' Simulates the impact of policy changes (e.g., area closures) or changes in exogenous 
#' variables (e.g., fuel prices, expected catch) on redistributed fishing effort and 
#' economic welfare.
#' 
#' \strong{How to use \code{data_modifiers}:}
#' To create counterfactual data vectors, be sure to include
#' your unique observation ID (e.g., trip or haul ID), date, and zone ID variables when 
#' formatting your data with \code{format_model_data()}. To guarantee the math aligns perfectly 
#' with the simulation matrices:
#' 
#' \enumerate{
#'   \item Load your saved long-format dataset.
#'   \item Apply your mathematical transformation or merge in your external counterfactual data.
#'   \item Pass the raw, modified vector into the \code{data_modifiers} argument as a named list 
#'    where the name exactly matches the column in the model 
#'    (e.g., \code{list(distance = new_dist)}). For EPM price modifications, strictly use 
#'    the name \code{"price"}.
#' }
#'
#' \strong{Analyzing results:}
#' Once your simulations have successfully run, use the companion summary functions to extract 
#' cleaned data frames and \code{ggplot2} visualizations:
#' \itemize{
#'   \item \code{\link{summarize_policy_welfare}}: Extracts compensating variation (economic 
#'   impact) metrics and generates bar and density plots.
#'   \item \code{\link{summarize_policy_effort}}: Extracts spatial effort redistribution and 
#'   generates absolute, percentage, and spillover scatter plots.
#' }
#'
#'
#' @param project Character. Name of the project.
#' @param mod_name Character. Name of the fitted model to use for the simulation.
#' @param closures List (Optional). A list of closure scenarios generated by zone_closure().
#' @param data_modifiers List (Optional). A named list of new data vectors to inject into the 
#'   model. Names must match variables in the model's design matrix or price vector.
#' @param betadraws Integer. Number of multivariate normal draws for the simulation. 
#'   Default is 1000.
#' @param marg_util_income Character. For standard/zonal logit models: Name of the coefficient 
#'   to use as the marginal utility of income to calculate welfare in dollars. Note this
#'   input will be ignored for EPMs.
#' @param income_cost Logical. Default FALSE. Set to TRUE if the `marg_util_income` parameter 
#'   represents a cost (flips the sign of the coefficient). Note this
#'   input will be ignored for EPMs.
#'
#' @return An object of class `fishset_policy` containing simulation results saved in the project
#'   database with the name [project]PolicySimulations.
#' @export
#' @seealso \code{\link{summarize_policy_welfare}}, \code{\link{summarize_policy_effort}}
#' @importFrom DBI dbConnect dbDisconnect dbExecute dbGetQuery
#' @importFrom RSQLite SQLite
#' @importFrom MASS mvrnorm
#' @examples
#' \dontrun{
#' # -----------------------------------------------------------------------
#' # Example 1: Standard Logit - Baseline & Closures
#' # -----------------------------------------------------------------------
#' # Run a baseline simulation (no closures)
#' run_simulation(
#'   project = "MyProject",
#'   mod_name = "clogit_model1",
#'   marg_util_income = "expected_catch"
#' )
#' 
#' # Run simulations for two separate spatial closures defined in your YAML
#' run_simulation(
#'   project = "MyProject",
#'   mod_name = "clogit_model1",
#'   closures = c("closure_1", "closure_2"),
#'   marg_util_income = "expected_catch"
#' )
#' 
#' # -----------------------------------------------------------------------
#' # Example 2: Standard Logit - Data Modifiers (e.g., Fuel Spike)
#' # -----------------------------------------------------------------------
#' library(data.table)
#' 
#' # 1. Load the formatted data to ensure perfect matrix alignment
#' # Note that this saves as a qs2 file if the package is available, and as a .rds file if not.
#' lf_data <- 
#'   qs2::qs_read("MyProject/Models/FormattedData/MyProjectLongFormatData.rds")[["format1"]]
#' # OR #
#' lf_data <- 
#'   readRDS("MyProject/Models/FormattedData/MyProjectLongFormatData.rds")[["format1"]]
#' new_distance <- as.numeric(lf_data$distance) * 1.5
#' 
#' # 2. Run the simulation
#' run_simulation(
#'   project = "MyProject",
#'   mod_name = "clogit_model1",
#'   data_modifiers = list(distance = new_distance), 
#'   marg_util_income = "expected_catch"
#' )
#' 
#' # -----------------------------------------------------------------------
#' # Example 3: Expected Profit Model - Closures AND Price Drop Combined
#' # -----------------------------------------------------------------------
#' # EPMs automatically calculate marginal utility of income, so it is omitted.
#' # The keyword "price" must be used for EPM revenue modifications.
#' 
#' new_price <- as.numeric(lf_data$price) * 0.80 # 20% price drop
#' 
#' run_simulation(
#'   project = "MyProject",
#'   mod_name = "epm_model1",
#'   closures = c("closure_1"),
#'   data_modifiers = list(price = new_price),
#'   betadraws = 1000
#' )
#' }

run_simulation <- function(project,
                           mod_name,
                           closures = NULL,
                           data_modifiers = NULL,
                           betadraws = 500,
                           marg_util_income = NULL,
                           income_cost = FALSE) {
  
  # Setup and database connection -----------------------------------------------------------------
  fishset_db <- DBI::dbConnect(RSQLite::SQLite(), locdatabase(project = project))
  on.exit(DBI::dbDisconnect(fishset_db), add = TRUE)
  
  # Load model design (X matrices, epm components, scalers)
  paths <- file.path(locproject(), project, "Models", "ModelDesigns", 
                     c(paste0(mod_name, ".qs2"), paste0(mod_name, ".rds")))
  found_path <- paths[file.exists(paths)][1]
  if (is.na(found_path)) stop(paste("Model design", mod_name, "not found. Run fishset_design()."))
  
  if (grepl("\\.qs2$", found_path)) {
    design <- qs2::qs_read(found_path)
  } else {
    design <- readRDS(found_path)
  }
  
  # Load Fitted Model
  fit_list <- unserialize_table(paste0(project, "ModelFit"), project)
  fit_name <- paste0(mod_name, "_fit")
  if (!(fit_name %in% names(fit_list))) {
    stop(paste("Model fit", fit_name, "not found. Run fishset_fit() first."))
  }
  fit <- fit_list[[fit_name]]
  
  # Delete the full fit_list
  rm(fit_list)
  
  is_epm <- isTRUE(design$epm$is_epm)
  N_obs <- design$settings$N_obs
  J_alts <- design$settings$J_alts
  
  # Auto-detect distribution for EPM
  if (is_epm) {
    coef_names <- names(fit$coefficients)
    if (any(grepl("Sigma_Catch_", coef_names))) {
      distribution <- "normal"
    } else if (any(grepl("Sdlog_Catch_", coef_names))) {
      distribution <- "lognormal"
    } else if (any(grepl("Shape_Catch_", coef_names))) {
      distribution <- "weibull"
    } else {
      stop("Could not infer EPM distribution from model fit coefficients.")
    }
  } else {
    distribution <- "logit"
  }
  
  # Extract data and parameter draws --------------------------------------------------------------
  # Create base matrices
  X_base <- design$X
  if (is_epm) {
    X_catch_base <- design$epm$X_catch
    price_base <- design$epm$price_vec
    
    # EPMs split the design matrix
    cost_cols <- setdiff(colnames(X_base), colnames(X_catch_base))
    X_cost_base <- X_base[, cost_cols, drop = FALSE]
  }
  
  # Check Hessian for valid covariance matrix
  hess <- fit$diagnostics$hessian
  if (is.null(hess) || any(is.na(hess))) {
    stop("Invalid Hessian matrix in model fit. Cannot generate parameter draws.")
  }
  
  cov_mat <- tryCatch(solve(hess), error = function(e) NULL)
  if (is.null(cov_mat)) stop("Hessian matrix is not invertible (not positive definite).")
  
  # Draw parameters from Multivariate Normal
  beta_draws <- MASS::mvrnorm(n = betadraws, mu = fit$opt$par, Sigma = cov_mat)
  colnames(beta_draws) <- names(fit$opt$par)
  
  # Apply data modifiers (counterfactual X) -------------------------------------------------------
  X_new <- X_base
  if (is_epm) {
    X_catch_new <- X_catch_base
    price_new <- price_base
  }
  
  if (!is.null(data_modifiers)) {
    for (var_name in names(data_modifiers)) {
      new_vec <- as.numeric(data_modifiers[[var_name]])
      var_found <- FALSE # set flag to false
      
      # Helper to apply scaling
      scale_new_data <- function(vec, var, scalers) {
        if (!is.null(scalers)) {
          # Check X1/X2 scalers
          sds <- c(scalers$X1$sd, unlist(scalers$X2$sd), 
                   scalers$X1_catch$sd, unlist(scalers$X2_catch$sd))
          mus <- c(scalers$X1$mu, unlist(scalers$X2$mu), 
                   scalers$X1_catch$mu, unlist(scalers$X2_catch$mu))
          if (var %in% names(sds)) {
            vec <- (vec - mus[var]) / sds[var]
          }
        }
        return(vec)
      }
      
      # Modify standard matrix
      if (var_name %in% colnames(X_new)) {
        X_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
        var_found <- TRUE # set flag
      }
      
      # Modify EPM matrices
      if (is_epm) {
        if (var_name %in% colnames(X_catch_new)) {
          X_catch_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
          var_found <- TRUE # set flag
        }
        if (var_name == "price") {
          p_div <- if (!is.null(design$scalers$price_divisor)) design$scalers$price_divisor else 1
          price_new <- new_vec / p_div
          var_found <- TRUE # set flag
        }
      }
      
      # Throw an error if the variable was not found
      if (!var_found) {
        stop(paste0(
          "Data modifier error. '", var_name, "' was not found in the model's dseign matrix ",
          "(or as 'price' in an EPM). Check for typos and ensure the variable name exactly ",
          "matches a column in your formatted data."
        ))
      }
    }
  }
  
  if (is_epm) {
    # Slice X_cost_new after X_new has been fully modified by the loop
    X_cost_new <- X_new[, cost_cols, drop = FALSE]
    
    y_div <- if (!is.null(design$scalers$Y_catch_divisor)) design$scalers$Y_catch_divisor else 1
    p_div <- if (!is.null(design$scalers$price_divisor)) design$scalers$price_divisor else 1
    epm_welfare_multiplier <- y_div * p_div
  }
  
  # Load closures from YAML -----------------------------------------------------------------------
  base_scenarios <- list()
  
  if (!is.null(closures)) {
    yaml_file <- paste0(locoutput(project), pull_output(project, 
                                                        type = "zone", 
                                                        fun = "closures"))
    if (utils::file_test("-f", yaml_file)) {
      all_closures <- yaml::read_yaml(yaml_file)
      
      # Filter to user-selected closures
      raw_scenarios <- all_closures[vapply(
        all_closures, 
        function(x) x$scenario %in% unlist(closures), logical(1))]
      
      if (length(raw_scenarios) == 0) {
        available_scens <- vapply(all_closures, function(x) x$scenario, character(1))
        stop(paste0("None of the specified scenario names in 'closures' were found in ",
                    "the YAML file.\n Available scenarios are: '", 
                    paste(available_scens, collapse = "', '"), "'"), call. = FALSE)
      }
      
      # Validate that all the closure zones exist in the model design
      available_design_zones <- as.character(unique(design$ids$zone))
      
      for (scen in raw_scenarios) {
        if (!is.null(scen$zone)) {
          # Strip the 'Zone_' prefix from the YAML definitions to match model ID format
          requested_zones <- gsub("Zone_", "", scen$zone)
          missing_zones <- setdiff(requested_zones, available_design_zones)
          
          if (length(missing_zones) > 0) {
            warning(sprintf(
              paste0("Closure scenario '%s' will not be simulated because one or more zones ",
                     "identified are not available in the model design choice set. ",
                     "Missing zones: %s"), 
              scen$scenario, 
              paste(missing_zones, collapse = ", ")
            ), call. = FALSE, immediate. = TRUE)
            next # Skip adding this scenario to base_scenarios
          }
        }
        # If valid, append to the final scenario list
        base_scenarios[[length(base_scenarios) + 1]] <- scen
      }
      
      # Safety check in case ALL selected scenarios were dropped due to invalid zones
      if (length(base_scenarios) == 0) {
        stop(paste0("Simulation aborted. None of the specified closure scenarios contain valid ",
                    "zones for this model design."), call. = FALSE)
      }
      
    } else {
      stop("No policy scenario YAML file found. Run the zone_closure() function first.")
    }
    
  } else {
    # Fallback base scenario if no closures are provided
    base_scenarios <- list(list(scenario = "baseline", zone = NULL))
  }
  
  # Merge data modifiers into the scenario names
  has_mods <- !is.null(data_modifiers)
  
  if (has_mods) {
    mod_vars <- paste(names(data_modifiers), collapse = "_")
    
    for (i in seq_along(base_scenarios)) {
      if (base_scenarios[[i]]$scenario == "baseline") {
        base_scenarios[[i]]$scenario <- mod_vars
      } else {
        # Combine the closure name and modifier name (e.g., "closure1_price")
        base_scenarios[[i]]$scenario <- paste0(base_scenarios[[i]]$scenario, "_", mod_vars)
      }
    }
  }
  
  # Find theta index
  if (!is_epm) {
    if (is.null(marg_util_income)) stop("Standard logit requires 'marg_util_income'.")
    theta_idx <- which(colnames(X_base) == marg_util_income)
    if (length(theta_idx) == 0) stop(paste("Coefficient", marg_util_income, "not found."))
    
  } else {
    # Warn the user if they mistakenly passed marginal utility of income for EPM
    if (!is.null(marg_util_income)) {
      warning(paste(
        "The 'marg_util_income' argument is ignored for Expected Profit Models (EPM).",
        "EPMs automatically calculate the marginal utility of income internally",
        "using the error variance parameter (1 / sigma_e)."
      ), call. = FALSE, immediate. = TRUE)
    }
  }
  
  scenarios <- base_scenarios
  results_list <- list()
  zone_vec <- as.character(design$ids$zone)
  # Extract the exact zone ID names for the J_alts
  real_zone_names <- zone_vec[1:J_alts]
  
  # Run simulation --------------------------------------------------------------------------------
  for (scen in scenarios) {
    scenario_name <- scen$scenario
    closed_zones <- if (!is.null(scen$zone)) gsub("Zone_", "", scen$zone) else character(0)
    closed_idx <- which(zone_vec %in% closed_zones)
    
    theta_flag <- FALSE
    
    draw_welfare <- numeric(betadraws)
    # Trackers for expected trips
    draw_trips_base <- matrix(NA_real_, nrow = betadraws, ncol = J_alts)
    draw_trips_new  <- matrix(NA_real_, nrow = betadraws, ncol = J_alts)
    
    for (d in 1:betadraws) {
      b_d <- beta_draws[d, ]
      
      if (!is_epm) {
        V_base <- as.numeric(X_base %*% b_d)
        if (has_mods) V_new <- as.numeric(X_new %*% b_d)
        
        theta <- b_d[theta_idx]
        if (income_cost) theta <- -theta
        
        # Unscale theta if necessary
        if (!is.null(design$scalers)) {
          # Combine all potential stdev scalers
          sds <- c(design$scalers$X1$sd, unlist(design$scalers$X2$sd))
          # If marg_util_income was scaled, divide by its stdev
          if (marg_util_income %in% names(sds)) {
            theta <- theta / sds[marg_util_income]
          }
        }
        
        # Error check: marginal utility of income must be positive
        if (theta <= 0) {
          theta_flag <- TRUE
          draw_welfare[d] <- NA
          next # skip and go to the next draw
        }
        
      } else {
        # Extract parameters
        n_c <- ncol(X_catch_base)
        n_var <- length(grep("log_sigma|Sigma|Sdlog|Shape", names(b_d), ignore.case = TRUE))
        n_u <- length(b_d) - n_c - n_var
        
        # Catch parameters are always the first n_c elements
        b_c <- b_d[1:n_c]
        
        # If X_base has columns, pull the matching parameters; otherwise leave empty
        if (n_u > 0) {
          b_u <- b_d[(n_c + 1):(n_c + n_u)]
        } else {
          b_u <- numeric(0)
        }
        
        sig_c <- exp(b_d[grep("log_sigma_c", names(b_d))])
        sig_e <- exp(b_d[grep("log_sigma_e", names(b_d))])
        
        lin_pred_base <- as.numeric(X_catch_base %*% b_c)
        if (has_mods) lin_pred_new <- as.numeric(X_catch_new %*% b_c)
        
        # Explicitly expand sig_c to match the length of the dataset
        zone_seq <- ((0:(length(lin_pred_base) - 1)) %% J_alts) + 1
        sig_c_full <- sig_c[zone_seq]
        
        if (distribution == "normal") {
          mu_catch_base <- lin_pred_base
          if (has_mods) mu_catch_new <- lin_pred_new
        } else if (distribution == "lognormal") {
          mu_catch_base <- exp(lin_pred_base + 0.5 * (sig_c_full^2))
          if (has_mods) mu_catch_new <- exp(lin_pred_new + 0.5 * (sig_c_full^2))
        } else if (distribution == "weibull") {
          mu_catch_base <- exp(lin_pred_base) * exp(lgamma(1 + 1 / sig_c_full))
          if (has_mods) mu_catch_new <- exp(lin_pred_new) * exp(lgamma(1 + 1 / sig_c_full))
        }
        
        rev_base <- price_base * mu_catch_base
        cost_base <- if (length(b_u) > 0) as.numeric(X_cost_base %*% b_u) else 0
        V_base <- (1 / sig_e) * (rev_base + cost_base)
        
        if (has_mods) {
          rev_new <- price_new * mu_catch_new
          cost_new <- if (length(b_u) > 0) as.numeric(X_cost_new %*% b_u) else 0
          V_new <- (1 / sig_e) * (rev_new + cost_new)
        }
        theta <- (1 / sig_e)
      }
      
      dim(V_base) <- c(J_alts, N_obs)
      
      # Fast Max for Base
      max_V_base <- V_base[1, ]
      for (j in 2:J_alts) {
        curr_base <- V_base[j, ]
        
        # which() filters out NA and NaN values to prevent subscript errors
        idx_base <- which(curr_base > max_V_base)
        if (length(idx_base) > 0) {
          max_V_base[idx_base] <- curr_base[idx_base]
        }
      }
      
      # Shift and exp Base
      for (j in 1:J_alts) {
        V_base[j, ] <- V_base[j, ] - max_V_base
      }
      V_base <- exp(V_base)
      
      # Base logsum and effort (Bypass S3 Overhead)
      sum_V_base <- .colSums(V_base, m = J_alts, n = N_obs, na.rm = FALSE)
      logsum_base <- log(sum_V_base) + max_V_base
      
      # Calculate expected trips/hauls per zone (sum of probabilities)
      draw_trips_base[d, ] <- rowSums(sweep(V_base, 2, sum_V_base, "/"), na.rm = TRUE)
      
      if (!has_mods) {
        # Skip V_new for data modifiers
        if (length(closed_idx) > 0) {
          V_base[closed_idx] <- 0 
        }
        sum_V_new <- .colSums(V_base, m = J_alts, n = N_obs, na.rm = FALSE)
        logsum_new <- log(sum_V_new) + max_V_base
        
        # Calculate counterfactual expected trips/hauls
        draw_trips_new[d, ] <- rowSums(sweep(V_base, 2, sum_V_new, "/"), na.rm = TRUE)
        
      } else {
        # If data changed, we must do the full CPU math for V_new
        if (length(closed_idx) > 0) V_new[closed_idx] <- -Inf
        dim(V_new) <- c(J_alts, N_obs)
        
        max_V_new <- V_new[1, ]
        for (j in 2:J_alts) {
          curr_new <- V_new[j, ]
          # Filter NAs for the counterfactual matrix
          idx_new <- which(curr_new > max_V_new)
          if (length(idx_new) > 0) max_V_new[idx_new] <- curr_new[idx_new]
        }
        
        for (j in 1:J_alts) {
          V_new[j, ] <- V_new[j, ] - max_V_new
        }
        
        V_new <- exp(V_new)
        sum_V_new <- .colSums(V_new, m = J_alts, n = N_obs, na.rm = FALSE)
        logsum_new <- log(sum_V_new) + max_V_new
        
        # Calculate counterfactual expected trips/hauls
        draw_trips_new[d, ] <- rowSums(sweep(V_new, 2, sum_V_new, "/"), na.rm = TRUE)
      }
      
      welfare_diff <- (1 / theta) * (logsum_new - logsum_base)
      
      if (is_epm) {
        welfare_diff <- welfare_diff * epm_welfare_multiplier
      }
      
      draw_welfare[d] <- mean(welfare_diff, na.rm = TRUE)
    }
    
    # Store scenario summaries
    avg_trips_base <- colMeans(draw_trips_base, na.rm = TRUE)
    avg_trips_new  <- colMeans(draw_trips_new, na.rm = TRUE)
    names(avg_trips_base) <- real_zone_names
    names(avg_trips_new)  <- real_zone_names
    
    results_list[[scenario_name]] <- list(
      welfare_draws = draw_welfare,
      mean_welfare_loss = mean(draw_welfare, na.rm = TRUE),
      quantiles = quantile(draw_welfare, probs = c(0.025, 0.05, 0.5, 0.95, 0.975), na.rm = TRUE),
      effort_base = avg_trips_base, 
      effort_new = avg_trips_new
    )
  }
  
  # Report theta_flag
  if (theta_flag) {
    warning(
      paste0("One or more draws for the marginal utility of income were <= 0, which returns NA ",
             "values. If the marginal utility of income is represented with a cost coefficient ",
             "(negative), then set income_cost = TRUE."
      )
    )
  }
  
  # Package and save ------------------------------------------------------------------------------
  table_name <- paste0(project, "PolicySimulations")
  
  # Load existing simulations master list
  full_sim_list <- tryCatch({
    unserialize_table(table_name, project)
  }, error = function(e) {
    list()
  })
  
  # Initialize the wrapper with the existing list
  sim_wrapper <- full_sim_list
  
# Package each scenario as its own independent top-level object
  for (scen_name in names(results_list)) {
    sim_obj <- list(
      model_name = mod_name,
      scenario = scen_name,
      results = results_list[[scen_name]],
      metadata = list(
        N_obs = N_obs,
        J_alts = J_alts,
        betadraws = betadraws,
        distribution = if (is_epm) distribution else "logit",
        marg_util_income = if (is.null(marg_util_income)) NA else marg_util_income, 
        income_cost = income_cost, 
        timestamp = Sys.time()
      )
    )
    class(sim_obj) <- "fishset_policy"
    
    # Create the exact naming convention: "modelName_scenarioName"
    sim_name <- paste0(mod_name, "_", scen_name)
    
    # Overwrite if exact name exists, otherwise append to the master list
    sim_wrapper[[sim_name]] <- sim_obj
  }
  
  # Save the updated master list back to the database
  if (table_exists(table_name, project)) {
    table_remove(table_name, project)
  }
  
  # Define the column type as BLOB
  DBI::dbExecute(fishset_db, 
                 paste("CREATE TABLE IF NOT EXISTS",
                       table_name,
                       "(data BLOB)"))
  
  # Explicitly map the insert to the 'data' column
  DBI::dbExecute(fishset_db,
                 paste("INSERT INTO",
                       table_name,
                       "(data) VALUES (:data)"),
                 params = list(data = list(serialize(sim_wrapper, NULL))))
  
  # Log the function call -------------------------------------------------------------------------
  fishset_sim_function <- list()
  fishset_sim_function$functionID <- "run_simulation"
  fishset_sim_function$args <- as.list(match.call())[-1]
  fishset_sim_function$kwargs <- list()
  
  # Assuming log_call is your internal package function
  log_call(project, fishset_sim_function)
  
  # Force R to clean up temporary matrices and return RAM to the OS
  gc() 
  return(invisible(results_list))
}