#' Run Policy and Data Simulations
#'
#' Simulates the impact of policy changes (e.g., area closures) or changes in exogenous 
#' variables (e.g., fuel prices, expected catch) on redistributed fishing effort and 
#' economic welfare.
#'
#' @param project Character. Name of the project.
#' @param mod_name Character. Name of the fitted model to use for the simulation.
#' @param closures List (Optional). A list of closure scenarios generated by zone_closure().
#' @param data_modifiers List (Optional). A named list of new data vectors to inject into the 
#'   model. Names must match variables in the model's design matrix or price vector.
#' @param betadraws Integer. Number of multivariate normal draws for the simulation. 
#'   Default is 1000.
#' @param marg_util_income Character. For standard/zonal logit models: Name of the coefficient 
#'   to use as the marginal utility of income to calculate welfare in dollars.
#' @param income_cost Logical. Default FALSE. Set to TRUE if the `marg_util_income` parameter 
#'   represents a cost (flips the sign of the coefficient).
#'
#' @return An object of class `fishset_policy` containing simulation results.
#' @export
#' @importFrom DBI dbConnect dbDisconnect dbExecute dbGetQuery
#' @importFrom RSQLite SQLite
#' @importFrom MASS mvrnorm

run_simulation <- function(project,
                           mod_name,
                           closures = NULL,
                           data_modifiers = NULL,
                           betadraws = 1000,
                           marg_util_income = NULL,
                           income_cost = FALSE) {
  
  # Setup and database connection -----------------------------------------------------------------
  fishset_db <- DBI::dbConnect(RSQLite::SQLite(), locdatabase(project = project))
  on.exit(DBI::dbDisconnect(fishset_db), add = TRUE)
  
  # Load model design (X matrices, epm components, scalers)
  paths <- file.path(locproject(), project, "Models", "ModelDesigns", 
                     c(paste0(mod_name, ".qs2"), paste0(mod_name, ".rds")))
  found_path <- paths[file.exists(paths)][1]
  if (is.na(found_path)) stop(paste("Model design", mod_name, "not found. Run fishset_design()."))
  
  if (grepl("\\.qs2$", found_path)) {
    design <- qs2::qs_read(found_path)
  } else {
    design <- readRDS(found_path)
  }
  
  # Load Fitted Model
  fit_list <- unserialize_table(paste0(project, "ModelFit"), project)
  fit_name <- paste0(mod_name, "_fit")
  if (!(fit_name %in% names(fit_list))) {
    stop(paste("Model fit", fit_name, "not found. Run fishset_fit() first."))
  }
  fit <- fit_list[[fit_name]]
  
  is_epm <- isTRUE(design$epm$is_epm)
  N_obs <- design$settings$N_obs
  J_alts <- design$settings$J_alts
  
  
  # Extract data and parameter draws --------------------------------------------------------------
  # Create base matrices
  X_base <- design$X
  if (is_epm) {
    X_catch_base <- design$epm$X_catch
    price_base <- design$epm$price_vec
  }
  
  # Check Hessian for valid covariance matrix
  hess <- fit$diagnostics$hessian
  if (is.null(hess) || any(is.na(hess))) {
    stop("Invalid Hessian matrix in model fit. Cannot generate parameter draws.")
  }
  cov_mat <- tryCatch(solve(hess), error = function(e) NULL)
  if (is.null(cov_mat)) stop("Hessian matrix is not invertible (not positive definite).")
  
  # Draw parameters from Multivariate Normal: rows = draws, cols = parameters
  beta_draws <- MASS::mvrnorm(n = betadraws, mu = fit$opt$par, Sigma = cov_mat)
  
  
  # Apply data modifiers (counterfactual X) -------------------------------------------------------
  X_new <- X_base
  if (is_epm) {
    X_catch_new <- X_catch_base
    price_new <- price_base
  }
  
  if (!is.null(data_modifiers)) {
    for (var_name in names(data_modifiers)) {
      new_vec <- data_modifiers[[var_name]]
      
      # Helper to apply FishSET scaling
      scale_new_data <- function(vec, var, scalers) {
        if (!is.null(scalers)) {
          # Check X1/X2 scalers
          sds <- c(scalers$X1$sd, unlist(scalers$X2$sd), 
                   scalers$X1_catch$sd, unlist(scalers$X2_catch$sd))
          mus <- c(scalers$X1$mu, unlist(scalers$X2$mu), 
                   scalers$X1_catch$mu, unlist(scalers$X2_catch$mu))
          if (var %in% names(sds)) {
            vec <- (vec - mus[var]) / sds[var]
          }
        }
        return(vec)
      }
      
      # Modify standard matrix
      if (var_name %in% colnames(X_new)) {
        X_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
      }
      
      # Modify EPM matrices
      if (is_epm) {
        if (var_name %in% colnames(X_catch_new)) {
          X_catch_new[, var_name] <- scale_new_data(new_vec, var_name, design$scalers)
        }
        if (var_name == "price") {
          p_div <- if (!is.null(design$scalers$price_divisor)) design$scalers$price_divisor else 1
          price_new <- new_vec / p_div
        }
      }
    }
  }
  
  
  
}