sparsetable <- function(dat, timevar, zonevar, var){
#' Sparsity table
#' @param dat Main data frame over which to apply function. 
#' @param timvar Variable containing temporal data 
#' @param zonevar Variable contianing zone observation assigned to
#' @param var Variable containing catch data
#' @description Function to create sparsity table
#' @importFrom lubridate round_date 
#' @importFrom reshape2 acast
#' @export
#'

spars <- function(x, dname){

      if(dname=='1 weeks'){
        rownames(x) = lubridate::round_date(as.Date(rownames(x)), "1 weeks")
      } else if(dname=='2 weeks'){
        rownames(x) = lubridate::round_date(as.Date(rownames(x)), "2 weeks")  
      } else if(dname=='3 months'){
        rownames(x) = lubridate::round_date(as.Date(rownames(x)), "3 months")  
        } else {
      rownames(x) = format(as.Date(rownames(x)), dname)
      }
      x <- suppressWarnings(aggregate(x, by=list(rownames(x)), FUN=sum)[,-1])
      x <- ifelse(x>0,1,0)
      x <- unique(x)
      #print(head(x))
      return(colSums(x == 0)/nrow(x))
      }
#browser()
tmp <- suppressWarnings(reshape2::acast(dat[,c(zonevar,var,timevar)], dat[[timevar]]~dat[[zonevar]], value.var=var))
tmp <- cbind(tmp, All_zones = rowSums(tmp))

sparstable <- matrix(nrow=6, ncol=length(colnames(tmp)))

sparstable[1,] <- spars(tmp, '%y%m%d')
sparstable[2,] <- spars(tmp, '1 weeks')
sparstable[3,] <- suppressWarnings(spars(tmp, '2 weeks'))
sparstable[4,] <- spars(tmp, '%y%m')
sparstable[5,] <- spars(tmp, '3 months')
sparstable[6,] <- spars(tmp, '%y')
  
colnames(sparstable) = names(spars(tmp, '%y'))
rownames(sparstable)=c('daily', 'weekly','biweekly','monthly', 'quarterly', 'yearly')
sparstable <- round(sparstable,2)
return(sparstable)
}



sparsplot <- function(x){

#' @param x output from spartstable function
#' @export
#' @importFrom reshape2 melt  
#' @details Returns a plot of sparsity values over time. Requires sparsity table generated by sparsetable function. 
library(ggplot2)

toplot <- reshape2::melt(x, id.vars = c("time"), measure.vars = colnames(x)[-length(colnames(x))])
toplot_sub <- data.frame(day=c(1,7,14,30,90,365), sparsity =apply(x, 1, mean))#x[,dim(x)[2]])
fit = lm (data = toplot_sub, sparsity ~ day)

g <- ggplot(data=toplot, aes(Var1,value, color=Var2)) + geom_point( show.legend = FALSE) +
    geom_smooth (aes(group=1, color='Mean of all zones'), method = "loess", size = 1, linetype = "dashed", se = FALSE,show.legend = FALSE) +
    stat_smooth(method = "nls", formula = "y ~ a*x^b",  
                method.args = list(start=c(a=fit$coefficients[[1]], b=fit$coefficients[[2]])), se = FALSE,show.legend = FALSE) +
    xlab('Time')+ylab('Sparsity value') + 
    theme(legend.title = element_blank()) +
    theme_bw (base_family = "Times") + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                                              panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
    guides (colour = guide_legend (override.aes = list(linetype = c(rep("blank", 5), "dashed", 'blank'))))
}






