sparsetable <- function(dat, project, timevar, zonevar, var) {
  #' Evaluate sparsity in data over time in table format
  #'
  #' Create table of data sparsity by predefined time periods.
  #' @param dat Primary data containing information on hauls or trips. Table in the FishSET database contains the string 'MainDataTable'.
  #' @param project String, name of project.
  #' @param timevar Variable in \code{dat} containing temporal data
  #' @param zonevar Variable in \code{dat} containing zone observation assigned to
  #' @param var Variable in \code{dat} containing catch data
  #' @importFrom lubridate round_date floor_date week
  #' @importFrom tidyr pivot_wider
  #' @export
  #'
  
  spars <- function(x, dates, dname) {
    if (dname == "1 weeks") {
      y <- lubridate::round_date(as.Date(dates), "1 weeks")
    } else if (dname == "2 weeks") {
      y <- lubridate::floor_date(as.Date(dates), 'year') + 
        14 * (lubridate::week(as.Date(dates)) %/% 2)
    } else if (dname == "3 months") {
      y <- lubridate::round_date(as.Date(dates), "3 months")
    } else {
      y <- format(as.Date(dates), dname)
    }
    x <- suppressWarnings(aggregate(x, by = list(y), FUN = sum)[, -1])
    x <- ifelse(x > 0, 1, 0)
    x <- unique(x)
    # print(head(x))
    return(colSums(x == 0) / nrow(x))
  }
  
  out <- data_pull(dat, project)
  dat <- parse_data_name(dat, "main", project)
  dataset <- out$dataset

  #tmp <- reshape2::acast(dataset[, c(zonevar, var, timevar)], dataset[[timevar]] ~ dataset[[zonevar]], value.var = var)
  tmp <-  as.data.frame(tidyr::pivot_wider(dataset[, c(zonevar, var, timevar)], names_from = all_of(zonevar), values_from = var, values_fn=length, values_fill=0))
  # rownames(tmp) <- tmp[1]
  
  dates <- tmp[[timevar]]
  tmp <- tmp[-1]
  # tmp <- cbind(tmp, All_zones = rowSums(tmp))
  tmp <- cbind(tmp, All_zones = rowSums(tmp))

  spars_tab <- matrix(nrow = 6, ncol = length(colnames(tmp)))

  spars_tab[1, ] <- spars(tmp, dates, "%y%m%d")
  spars_tab[2, ] <- spars(tmp, dates, "1 weeks")
  spars_tab[3, ] <- suppressWarnings(spars(tmp, dates, "2 weeks"))
  spars_tab[4, ] <- spars(tmp, dates, "%y%m")
  spars_tab[5, ] <- spars(tmp, dates, "3 months")
  spars_tab[6, ] <- spars(tmp, dates, "%y")

  colnames(spars_tab) <- names(spars(tmp, dates, "%y"))
  rownames(spars_tab) <- c("daily", "weekly", "biweekly", "monthly", "quarterly", "yearly")
  spars_tab <- round(spars_tab, 2)


  # Log the function

  sparsetable_function <- list()
  sparsetable_function$functionID <- "sparsetable"
  sparsetable_function$args <- list(dat, project, timevar, zonevar, var)
  log_call(project, sparsetable_function)


  save_table(spars_tab, project, "sparstable")
  return(spars_tab)
}



sparsplot <- function(project, x = NULL) {
  #' Evaluate sparsity in data over time in plot format
  #' @param x Output from \code{sparsetable}. If \code{x} is null, the sparsity table will be pulled from the output folder if it exists.
  #' @param project String, name of project.
  #' @export
  #' @import ggplot2
  #' @importFrom stats lm
  #' @importFrom tidyr gather
  #' @details Returns a plot of sparsity values over time.
  #' Requires sparsity table generated by \code{sparsetable}.
  requireNamespace("ggplot2")
  
  endrun <- 0
  variable = c()
  value = c()
  Period = c()

  
  if(is.null(x)){
  name <- pull_output(project, 'sparstable', type='table')
    if(!is.null(name)){
      x <- read.csv(paste0(locoutput(project=project), name))
      colnames(x)[1] <- 'Period'
    } else {
      message('Sparsity table not found. Create a sparsity table with sparsetable() function. Function was not run.')
      endrun <- 1
    }
  } else {
    x <- cbind(as.data.frame(rownames(x)),x)
    colnames(x)[1] <- 'Period'
  }

  if (endrun == 0){
  toplot <- tidyr::gather(as.data.frame(x), variable, value, -Period)
  #reshape2::melt(x, id.vars = c("time"), measure.vars = colnames(x)[-length(colnames(x))])
  toplot_sub <- data.frame(day = c(1, 7, 14, 30, 90, 365), sparsity = apply(x[,-1], 1, mean)) # x[,dim(x)[2]])
  fit <- stats::lm(data = toplot_sub, sparsity ~ day)

  g <- ggplot2::ggplot(data = toplot, ggplot2::aes(Period, value, color = variable)) +
    ggplot2::geom_point(show.legend = FALSE) +
    ggplot2::geom_smooth(ggplot2::aes(group = 1, color = "Mean of all zones"), method = "loess", size = 1, linetype = "dashed", se = FALSE, show.legend = FALSE) +
    ggplot2::stat_smooth(method = "nls", formula = "y ~ a*x^b", method.args = list(start = c(a = fit$coefficients[[1]],
                                                                                             b = fit$coefficients[[2]])), se = FALSE, show.legend = FALSE) +
    ggplot2::xlab("Time") +
    ggplot2::ylab("Sparsity value") +
    ggplot2::theme(legend.title = ggplot2::element_blank()) +
    ggplot2::theme(
      panel.border = ggplot2::element_blank(), panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
      panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
      axis.text = ggplot2::element_text(size = 11), axis.title = ggplot2::element_text(size = 11)
    ) +
    ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(linetype = c(rep("blank", 5), "dashed", "blank"))))



  sparsplot_function <- list()
  sparsplot_function$functionID <- "sparsplot"
  sparsplot_function$args <- list(project, deparse(substitute(x)))
  log_call(project, sparsplot_function)

  
  print(g)  
  save_plot(project, "sparsplot", g)

  }
}
